---
title: "p8105_hw1_ay2452"
author: "Alicia Yang"
date: "9/19/2019"
output: github_document
---

```{r problem 1.1}
library(tidyverse)

set.seed(10) 

problem1_df = tibble(
  norm_samp = rnorm(8),
  a_samp_pos = (norm_samp > 0),
  b_char = c("one", "two", "three", "four", "five", "six", "seven", "eight"), 
  c_factor = factor(c("small", "medium", "big", "small", "medium", "big", "small", "medium" ), 
    levels = 1:3, labels = c("small", "medium", "big"))
)
```

```{r problem 1.2}
mean(pull(problem1_df,a_samp_pos))
mean(pull(problem1_df,b_char))
mean(pull(problem1_df,c_factor))
##Taking the mean of the logical vector works but taking the mean of the character and factor variables does not; the error says that the 'argument is not numeric or logical'
```


```{r problem 1.3, eval = FALSE}
as.numeric(pull(problem1_df,a_samp_pos))
as.numeric(pull(problem1_df,b_char))
as.numeric(pull(problem1_df,c_factor)) 
##Only the logical vector is able to be converted to a numeric vector because the other vectors do not consist of numbers. 
##This helps explain why taking the mean of the character and factor variables does not work since again, those vectors are not made of numbers.
```

```{r problem 1.4}
ab = as.numeric(pull(problem1_df,a_samp_pos))
pull(problem1_df,norm_samp)*ab
ac = as.factor(pull(problem1_df,a_samp_pos))
pull(problem1_df,norm_samp)*ac
ad = as.numeric(ac)
pull(problem1_df,norm_samp)*ad
```

```{r problem 2.1}
set.seed(1000)

problem2_df = tibble(
  x = rnorm(500),
  y = rnorm(500),
  z = c(x + y > 1),
  z_numeric = as.numeric(z),
  z_factor = as.factor(z)
)
```